### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by elfring** [Harha/MirageRender#2]
I suggest to reuse a higher level build system than [your current small make file](https://github.com/Harha/MirageRender/blob/55024ea404d664a0e2720d536b898ab831496793/Makefile#L1) so that powerful checks for software features will become easier.
- [CMake](https://cmake.org/)
- [Autotools](https://www.gnu.org/software/autoconf/autoconf.html#introduction)

**Comment by Harha** [comment]
I have thought of this but I've let it be as-is for now. CMake can be amazing, I agree completely. I just don't have any experience about it.

In the future I will surely create a more sophisticated way of building the project with the help of cmake. Some evening, when I have the interest and spare time to do so.

**Comment by fnky** [comment]
Could be nice to use in the future, for better multi OS support, but the Makefile isn't that clustered yet, so I don't see any benefit at the moment either.

**Comment by elfring** [comment]
- Does [a tool like "autoscan"](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/autoscan-Invocation.html) show any software dependencies that you find worth for further considerations?
- How do you think about to support more development environments by [the reuse of build system generators](https://cmake.org/cmake/help/v3.6/manual/cmake-generators.7.html#cmake-generators)?

**Comment by Harha** [comment]
I haven't had time to try out autoscan yet, sorry. I will though.

Anyways, old Makefile is now gone and CMakeLists.txt is the only way to generate a build environment. It seems to work fine on Windows 10 and Debian testing x64 but since it's the first CMakeLists.txt I have ever created it may need some refining.

**Comment by elfring** [comment]
Thanks for [your improvements around the CMake build script](https://github.com/Harha/MirageRender/commit/fb3f01a3fbf64ac68102dc1e16594104a6c188b4).
